//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_MVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tstAtistirmalikTable
    {
        public int id { get; set; }
        public string AtistirmalikAdi { get; set; }
        public string Aciklama { get; set; }
        public string Fiyat { get; set; }
        public string ResimYol { get; set; }
    }
}
