//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_MVC1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tstTable
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Kullanýcý Ad Alaný Boþ Býrakýlamaz")]
        public string userName { get; set; }

        [Required(ErrorMessage = "Þifre Alaný Boþ Býrakýlamaz")]
        public string password { get; set; }

        public string rank { get; set; }
    }
}
